### ISSUE TITLE
Local planner environmet vairable is not set

### ISSUE THREAD

**Issue by lioneleeedadad** [PX4/avoidance#391] opened 2019-05-31 09:08 UTC
omar@omar-Lenovo-ideapad-320-15IKB:~/catkin_ws$ roslaunch local_planner local_planner_sitl_3cam.launch
... logging to /home/omar/.ros/log/5444ea26-8383-11e9-9e1b-e82a44e20f6f/roslaunch-omar-Lenovo-ideapad-320-15IKB-4026.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

environment variable 'GAZEBO_MODEL_PATH' is not set
The traceback for the exception was written to the log file

**Comment by nicovanduijn** [comment] 2019-05-31 09:56
duplicate of #383

**Closed by nicovanduijn** 2019-05-31 09:56 UTC
