### ISSUE TITLE
local planner error 

### ISSUE THREAD

**Issue by lioneleeedadad** [PX4/avoidance#322] opened 2019-04-23 08:20 UTC
'm unable to see the tree obstacles also I can't move the drone using the 2D nav goal in RVIZ .. what can I do ? Also when I rosrun mavros mavsys mode -c OFFBOARD .. I get "Timed out!"
![image](https://user-images.githubusercontent.com/48925133/56565768-1c350700-657f-11e9-86ce-843800a6b8ef.png)
![image](https://user-images.githubusercontent.com/48925133/56565789-26570580-657f-11e9-9fcc-0457adc7ef45.png)
![image](https://user-images.githubusercontent.com/48925133/56565860-56060d80-657f-11e9-8eae-c97c76f340df.png)

**Comment by julianoes** [comment] 2019-04-24 13:50
Looks like a duplicate of #321.

**Closed by julianoes** 2019-04-24 13:50 UTC
