### ISSUE TITLE
Hello guys .. I have an issue where the rqt is opening but it doesn’t show the local planner node .. when I tried to do rosrun rqt_reconfigure rqt_reconfigure nothing change ! What can I do about that ? 

### ISSUE THREAD

**Issue by Omar1710** [PX4/avoidance#272] opened 2019-03-29 07:58 UTC

**Comment by jkflying** [comment] 2019-03-29 10:53
Duplicate of #267

**Closed by jkflying** 2019-03-29 10:53 UTC

**Comment by Omar1710** [comment] 2019-03-29 11:37
@jkflying Yes but this issue is not solves yet
