### ISSUE TITLE
rosrun mavros mavsys mode -c OFFBOARD does not work

### ISSUE THREAD

**Issue by woongjoonchoi** [PX4/avoidance#530] opened 2019-11-17 14:21 UTC
**Describe the bug**
rosrun mavros mavsys mode -c OFFBOARD
Timed out!

rosrun mavros mavsafety arm
it' work . arming is done.

OFFBOARD mode does not work
**To Reproduce**
1. Drone switched on '...'
I just do simulation followed by avoidance git
2. Uploaded mission '....' (attach QGC mission file)
um.. idont know

3. Took off '....'
i  command take off  work.

rosrun mavros mavsys mode -c OFFBOARD
Timed out!
**Expected behavior**

**Log Files and Screenshots**
*Always* provide a link to the flight log file:
- Download the flight log file from the vehicle ([tutorial](https://docs.px4.io/en/getting_started/flight_reporting.html)) or from the Gazebo simulation (logs are located in `~/.ros/logs/`)
- Share the link to a log showing the problem on [PX4 Flight Review](http://logs.px4.io/).
- Share a link to a rosbag showing the problem
ecking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://oongjoon-VivoBook-ASUSLaptop-X512DA-R564DA:42851/

SUMMARY
========

CLEAR PARAMETERS
 * /mavros/

PARAMETERS
 * /gazebo/enable_ros_network: True
 * /local_planner_node/goal_x_param: 17
 * /local_planner_node/goal_y_param: 15
 * /local_planner_node/goal_z_param: 3
 * /local_planner_node/pointcloud_topics: ['/realsense/came...
 * /local_planner_node/world_name: /home/oongjoon/ca...
 * /mavros/cmd/use_comp_id_system_control: False
 * /mavros/conn/heartbeat_rate: 1.0
 * /mavros/conn/system_time_rate: 1.0
 * /mavros/conn/timeout: 10.0
 * /mavros/conn/timesync_rate: 10.0
 * /mavros/distance_sensor/hrlv_ez4_pub/field_of_view: 0.0
 * /mavros/distance_sensor/hrlv_ez4_pub/frame_id: hrlv_ez4_sonar
 * /mavros/distance_sensor/hrlv_ez4_pub/id: 0
 * /mavros/distance_sensor/hrlv_ez4_pub/orientation: ROLL_180
 * /mavros/distance_sensor/hrlv_ez4_pub/send_tf: True
 * /mavros/distance_sensor/hrlv_ez4_pub/sensor_position/x: 0.0
 * /mavros/distance_sensor/hrlv_ez4_pub/sensor_position/y: 0.0
 * /mavros/distance_sensor/hrlv_ez4_pub/sensor_position/z: -0.1
 * /mavros/distance_sensor/laser_1_sub/id: 3
 * /mavros/distance_sensor/laser_1_sub/orientation: ROLL_180
 * /mavros/distance_sensor/laser_1_sub/subscriber: True
 * /mavros/distance_sensor/lidarlite_pub/field_of_view: 0.0
 * /mavros/distance_sensor/lidarlite_pub/frame_id: lidarlite_laser
 * /mavros/distance_sensor/lidarlite_pub/id: 1
 * /mavros/distance_sensor/lidarlite_pub/orientation: ROLL_180
 * /mavros/distance_sensor/lidarlite_pub/send_tf: True
 * /mavros/distance_sensor/lidarlite_pub/sensor_position/x: 0.0
 * /mavros/distance_sensor/lidarlite_pub/sensor_position/y: 0.0
 * /mavros/distance_sensor/lidarlite_pub/sensor_position/z: -0.1
 * /mavros/distance_sensor/sonar_1_sub/id: 2
 * /mavros/distance_sensor/sonar_1_sub/orientation: ROLL_180
 * /mavros/distance_sensor/sonar_1_sub/subscriber: True
 * /mavros/fcu_protocol: v2.0
 * /mavros/fcu_url: udp://:14540@loca...
 * /mavros/gcs_url: 
 * /mavros/global_position/frame_id: fcu
 * /mavros/global_position/rot_covariance: 99999.0
 * /mavros/global_position/tf/child_frame_id: fcu_utm
 * /mavros/global_position/tf/frame_id: local_origin
 * /mavros/global_position/tf/send: False
 * /mavros/image/frame_id: px4flow
 * /mavros/imu/angular_velocity_stdev: 0.0003490659 // 0...
 * /mavros/imu/frame_id: fcu
 * /mavros/imu/linear_acceleration_stdev: 0.0003
 * /mavros/imu/magnetic_stdev: 0.0
 * /mavros/imu/orientation_stdev: 1.0
 * /mavros/local_position/frame_id: local_origin
 * /mavros/local_position/tf/child_frame_id: fcu
 * /mavros/local_position/tf/frame_id: local_origin
 * /mavros/local_position/tf/send: True
 * /mavros/local_position/tf/send_fcu: False
 * /mavros/mission/pull_after_gcs: True
 * /mavros/mocap/use_pose: False
 * /mavros/mocap/use_tf: True
 * /mavros/plugin_blacklist: ['safety_area', '...
 * /mavros/plugin_whitelist: []
 * /mavros/px4flow/frame_id: px4flow
 * /mavros/px4flow/ranger_fov: 0.118682
 * /mavros/px4flow/ranger_max_range: 5.0
 * /mavros/px4flow/ranger_min_range: 0.3
 * /mavros/safety_area/p1/x: 1.0
 * /mavros/safety_area/p1/y: 1.0
 * /mavros/safety_area/p1/z: 1.0
 * /mavros/safety_area/p2/x: -1.0
 * /mavros/safety_area/p2/y: -1.0
 * /mavros/safety_area/p2/z: -1.0
 * /mavros/setpoint_accel/send_force: False
 * /mavros/setpoint_attitude/reverse_throttle: False
 * /mavros/setpoint_attitude/tf/child_frame_id: attitude
 * /mavros/setpoint_attitude/tf/frame_id: local_origin
 * /mavros/setpoint_attitude/tf/listen: False
 * /mavros/setpoint_attitude/tf/rate_limit: 10.0
 * /mavros/setpoint_position/tf/child_frame_id: setpoint
 * /mavros/setpoint_position/tf/frame_id: local_origin
 * /mavros/setpoint_position/tf/listen: False
 * /mavros/setpoint_position/tf/rate_limit: 50.0
 * /mavros/startup_px4_usb_quirk: True
 * /mavros/sys/disable_diag: False
 * /mavros/sys/min_voltage: 10.0
 * /mavros/target_component_id: 1
 * /mavros/target_system_id: 1
 * /mavros/tdr_radio/low_rssi: 40
 * /mavros/time/time_ref_source: fcu
 * /mavros/time/timesync_avg_alpha: 0.6
 * /mavros/vibration/frame_id: vibration
 * /mavros/vision_pose/tf/child_frame_id: vision
 * /mavros/vision_pose/tf/frame_id: local_origin
 * /mavros/vision_pose/tf/listen: False
 * /mavros/vision_pose/tf/rate_limit: 10.0
 * /mavros/vision_speed/listen_twist: False
 * /rosdistro: melodic
 * /rosversion: 1.14.3
 * /use_sim_time: True

NODES
  /
    convert_metric (nodelet/nodelet)
    gazebo (gazebo_ros/gzserver)
    local_planner_node (local_planner/local_planner_node)
    mavros (mavros/mavros_node)
    points_xyz (nodelet/nodelet)
    rqt_reconfigure (rqt_reconfigure/rqt_reconfigure)
    rviz (rviz/rviz)
    sitl_0 (px4/px4)
    spawn_model (gazebo_ros/spawn_model)
    standalone_nodelet (nodelet/nodelet)
    tf_depth_camera (tf/static_transform_publisher)

auto-starting new master
process[master]: started with pid [15033]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 9b3cb0a4-0942-11ea-ba92-907841b48da4
process[rosout-1]: started with pid [15044]
started core service [/rosout]
process[tf_depth_camera-2]: started with pid [15052]
process[rqt_reconfigure-3]: started with pid [15053]
process[sitl_0-4]: started with pid [15061]
INFO  [px4] PX4 daemon already running for instance 0 (Resource temporarily unavailable)
process[mavros-5]: started with pid [15062]
process[gazebo-6]: started with pid [15063]
process[spawn_model-7]: started with pid [15067]
process[local_planner_node-8]: started with pid [15073]
process[standalone_nodelet-9]: started with pid [15075]
[sitl_0-4] process has died [pid 15061, exit code 255, cmd /home/oongjoon/Firmware/build/px4_sitl_default/bin/px4 /home/oongjoon/Firmware/ROMFS/px4fmu_common -s etc/init.d-posix/rcS -i 0 -d __name:=sitl_0 __log:=/home/oongjoon/.ros/log/9b3cb0a4-0942-11ea-ba92-907841b48da4/sitl_0-4.log].
log file: /home/oongjoon/.ros/log/9b3cb0a4-0942-11ea-ba92-907841b48da4/sitl_0-4*.log
process[convert_metric-10]: started with pid [15076]
process[points_xyz-11]: started with pid [15077]
process[rviz-12]: started with pid [15089]
[ INFO] [1573999227.884613084]: Initializing nodelet with 8 worker threads.
[ INFO] [1573999227.925675934]: FCU URL: udp://:14540@localhost:14557
[ INFO] [1573999227.939132547]: udp0: Bind address: 0.0.0.0:14540
[ INFO] [1573999227.939339781]: udp0: Remote address: 127.0.0.1:14557
[ INFO] [1573999227.939532878]: GCS bridge disabled
[ INFO] [1573999227.942043686]: udp0: Remote address: 127.0.0.1:14580
[ INFO] [1573999227.953339063]: Initializing nodelet with 8 worker threads.
[ INFO] [1573999227.965692694]: Plugin 3dr_radio loaded
[ INFO] [1573999227.969501815]: Plugin 3dr_radio initialized
[ INFO] [1573999227.969641187]: Plugin actuator_control loaded
[ INFO] [1573999227.979728676]: Plugin actuator_control initialized
[ INFO] [1573999227.986059898]: Plugin adsb loaded
[ INFO] [1573999227.994494463]: Plugin adsb initialized
[ INFO] [1573999227.994687650]: Plugin altitude loaded
[ INFO] [1573999227.997975114]: Plugin altitude initialized
[ INFO] [1573999227.998298314]: Plugin cam_imu_sync loaded
[ INFO] [1573999228.004345813]: Plugin cam_imu_sync initialized
[ INFO] [1573999228.004584007]: Plugin command loaded
[ INFO] [1573999228.022503825]: Plugin command initialized
[ INFO] [1573999228.022768331]: Plugin companion_process_status loaded
[ INFO] [1573999228.028261998]: Plugin companion_process_status initialized
[ INFO] [1573999228.028454033]: Plugin debug_value loaded
[ INFO] [1573999228.047275189]: Plugin debug_value initialized
[ INFO] [1573999228.047479948]: Plugin distance_sensor blacklisted
[ INFO] [1573999228.047767660]: Plugin fake_gps loaded
[ INFO] [1573999228.069906588]: Plugin fake_gps initialized
[ INFO] [1573999228.070158259]: Plugin ftp loaded
[ INFO] [1573999228.089568966]: Plugin ftp initialized
[ INFO] [1573999228.089771852]: Plugin global_position loaded
[ INFO] [1573999228.109721068]: rviz version 1.13.5
[ INFO] [1573999228.109789842]: compiled against Qt version 5.9.5
[ INFO] [1573999228.109805853]: compiled against OGRE version 1.9.0 (Ghadamon)
[ INFO] [1573999228.141677098]: Forcing OpenGl version 0.
[ INFO] [1573999228.143756144]: Plugin global_position initialized
[ INFO] [1573999228.143935774]: Plugin gps_rtk loaded
[ INFO] [1573999228.153048591]: Plugin gps_rtk initialized
[ INFO] [1573999228.153424234]: Plugin hil loaded
[ INFO] [1573999228.206252792]: Plugin hil initialized
[ INFO] [1573999228.206526696]: Plugin home_position loaded
[ INFO] [1573999228.211306881]: Plugin home_position initialized
[ INFO] [1573999228.211471643]: Plugin imu loaded
[ INFO] [1573999228.220173238]: Plugin imu initialized
[ INFO] [1573999228.220624478]: Plugin landing_target loaded
[ INFO] [1573999228.232213185]: Plugin landing_target initialized
[ INFO] [1573999228.232400811]: Plugin local_position loaded
[ INFO] [1573999228.243599618]: Plugin local_position initialized
[ INFO] [1573999228.243804327]: Plugin log_transfer loaded
[ INFO] [1573999228.249801577]: Plugin log_transfer initialized
[ INFO] [1573999228.249972340]: Plugin manual_control loaded
[ INFO] [1573999228.254409075]: Plugin manual_control initialized
[ INFO] [1573999228.254618404]: Plugin mocap_pose_estimate loaded
[ INFO] [1573999228.259936288]: Plugin mocap_pose_estimate initialized
[ INFO] [1573999228.260190894]: Plugin mount_control loaded
[ INFO] [1573999228.265750971]: Plugin mount_control initialized
[ INFO] [1573999228.265956462]: Plugin obstacle_distance loaded
[ INFO] [1573999228.269770302]: Plugin obstacle_distance initialized
[ INFO] [1573999228.269984840]: Plugin odom loaded
[ INFO] [1573999228.277312715]: Plugin odom initialized
[ INFO] [1573999228.277539488]: Plugin onboard_computer_status loaded
[ INFO] [1573999228.281464765]: Plugin onboard_computer_status initialized
[ INFO] [1573999228.281751004]: Plugin param loaded
[ INFO] [1573999228.286375034]: Plugin param initialized
[ INFO] [1573999228.286549515]: Plugin px4flow loaded
[ INFO] [1573999228.299281422]: Plugin px4flow initialized
[ INFO] [1573999228.299399332]: Plugin rangefinder blacklisted
[ INFO] [1573999228.299702593]: Plugin rc_io loaded
[ INFO] [1573999228.304125622]: Plugin rc_io initialized
[ INFO] [1573999228.304221038]: Plugin safety_area blacklisted
[ INFO] [1573999228.304442159]: Plugin setpoint_accel loaded
[ INFO] [1573999228.309995192]: Plugin setpoint_accel initialized
[ INFO] [1573999228.310397187]: Plugin setpoint_attitude loaded
[ INFO] [1573999228.321891920]: Plugin setpoint_attitude initialized
[ INFO] [1573999228.322173870]: Plugin setpoint_position loaded
[ INFO] [1573999228.344463914]: Plugin setpoint_position initialized
[ INFO] [1573999228.344650648]: Plugin setpoint_raw loaded
[ INFO] [1573999228.361332030]: Plugin setpoint_raw initialized
[ INFO] [1573999228.361510979]: Plugin setpoint_velocity loaded
[ INFO] [1573999228.372365534]: Plugin setpoint_velocity initialized
[ INFO] [1573999228.372667002]: Plugin sys_status loaded
[ INFO] [1573999228.388391768]: Plugin sys_status initialized
[ INFO] [1573999228.388594113]: Plugin sys_time loaded
[ INFO] [1573999228.398363030]: TM: Timesync mode: MAVLINK
[ INFO] [1573999228.399996136]: Plugin sys_time initialized
[ INFO] [1573999228.400150236]: Plugin trajectory loaded
[ INFO] [1573999228.408646060]: Plugin trajectory initialized
[ INFO] [1573999228.409269967]: Plugin vfr_hud loaded
[ INFO] [1573999228.410522220]: Plugin vfr_hud initialized
[ INFO] [1573999228.410704525]: Plugin vibration blacklisted
[ INFO] [1573999228.410926278]: Plugin vision_pose_estimate loaded
[ INFO] [1573999228.424880300]: Plugin vision_pose_estimate initialized
[ INFO] [1573999228.425065611]: Plugin vision_speed_estimate loaded
[ INFO] [1573999228.435381836]: Plugin vision_speed_estimate initialized
[ INFO] [1573999228.435576345]: Plugin waypoint loaded
[ INFO] [1573999228.443461307]: Plugin waypoint initialized
[ INFO] [1573999228.443583366]: Plugin wheel_odometry blacklisted
[ INFO] [1573999228.443807813]: Plugin wind_estimation loaded
[ INFO] [1573999228.444780812]: Plugin wind_estimation initialized
[ INFO] [1573999228.444857381]: Autostarting mavlink via USB on PX4
[ INFO] [1573999228.444910174]: Built-in SIMD instructions: SSE, SSE2
[ INFO] [1573999228.444947677]: Built-in MAVLink package version: 2019.11.11
[ INFO] [1573999228.444985291]: Known MAVLink dialects: common ardupilotmega ASLUAV autoquad icarous matrixpilot paparazzi slugs standard uAvionix ualberta
[ INFO] [1573999228.445016992]: MAVROS started. MY ID 1.240, TARGET ID 1.1
[ INFO] [1573999228.459208086]: IMU: High resolution IMU detected!
[ INFO] [1573999228.459366555]: IMU: Attitude quaternion IMU detected!
[ INFO] [1573999228.497211874]: Stereo is NOT SUPPORTED
[ INFO] [1573999228.497396604]: OpenGl version: 4.5 (GLSL 4.5).
[gazebo-6] process has died [pid 15063, exit code 255, cmd /opt/ros/melodic/lib/gazebo_ros/gzserver -e ode /home/oongjoon/catkin_ws/src/avoidance/avoidance/sim/worlds/simple_obstacle.world __name:=gazebo __log:=/home/oongjoon/.ros/log/9b3cb0a4-0942-11ea-ba92-907841b48da4/gazebo-6.log].
log file: /home/oongjoon/.ros/log/9b3cb0a4-0942-11ea-ba92-907841b48da4/gazebo-6*.log
[INFO] [1573999228.986177, 0.000000]: Loading model XML from Gazebo Model Database
[INFO] [1573999228.988494, 0.000000]: Waiting for service /gazebo/spawn_sdf_model
[ WARN] [1573999228.999655209]: TM : RTT too high for timesync: 18446743376945.55 ms.
[ INFO] [1573999229.398649410]: CON: Got HEARTBEAT, connected. FCU: PX4 Autopilot
[ INFO] [1573999229.410461822]: IMU: High resolution IMU detected!
[ INFO] [1573999229.410674947]: IMU: Attitude quaternion IMU detected!
[ WARN] [1573999229.598216421]: TM : RTT too high for timesync: 18446743376345.55 ms.
[ WARN] [1573999230.197968023]: TM : RTT too high for timesync: 18446743375745.55 ms.
[ WARN] [1573999230.800706755]: TM : RTT too high for timesync: 18446743375145.55 ms.
[ WARN] [1573999231.398853514]: TM : RTT too high for timesync: 18446743374545.55 ms.
[ WARN] [1573999231.999751216]: TM : RTT too high for timesync: 18446743373945.55 ms.
[ WARN] [1573999232.600879980]: TM : RTT too high for timesync: 18446743373345.55 ms.
[ERROR] [1573999233.102927801]: PR: Unknown parameter to get: MPC_ACC_HOR
[ERROR] [1573999233.104383059]: PR: Unknown parameter to get: MPC_XY_CRUISE
[ERROR] [1573999233.105895208]: PR: Unknown parameter to get: CP_DIST
[ERROR] [1573999233.107310799]: PR: Unknown parameter to get: MPC_LAND_SPEED
[ERROR] [1573999233.108885429]: PR: Unknown parameter to get: MPC_JERK_MAX
[ERROR] [1573999233.110456393]: PR: Unknown parameter to get: NAV_ACC_RAD
[ WARN] [1573999233.201444711]: TM : RTT too high for timesync: 18446743372745.55 ms.
[ WARN] [1573999233.801894592]: TM : RTT too high for timesync: 18446743372145.55 ms.
[ WARN] [1573999234.402660403]: TM : RTT too high for timesync: 18446743371545.55 ms.
[ WARN] [1573999235.004783979]: TM : RTT too high for timesync: 18446743370945.55 ms.
[ WARN] [1573999235.604961862]: TM : RTT too high for timesync: 18446743370345.55 ms.
[ WARN] [1573999236.206380010]: TM : RTT too high for timesync: 18446743369745.55 ms.
[ WARN] [1573999236.806555972]: TM : RTT too high for timesync: 18446743369145.55 ms.
[ WARN] [1573999237.407413436]: TM : RTT too high for timesync: 18446743368545.55 ms.

**Additional context**

**Comment by Jaeyoung-Lim** [comment] 2019-11-17 14:41
This is a duplicate of https://github.com/mavlink/mavros/issues/1352 and not a issue of avoidance

**Closed** 2019-11-17 15:38 UTC
